// swift-tools-version: 5.9
// Generated by scripts/update-package-swift.sh.
// Run this script before tagging a release so the binaryTarget URL and checksum
// match the GitHub release asset uploaded by .github/workflows/release.yml.
import PackageDescription

let package = Package(
    name: "MeshLink",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "MeshLink",
            targets: ["MeshLink"],
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MeshLink",
            url: "https://github.com/trancee/meshlink/releases/download/v0.1.0/MeshLink.xcframework.zip",
            checksum: "REPLACE_WITH_RELEASE_CHECKSUM",
        ),
    ],
)
