package ch.trancee.meshlink.wire

public enum class ValidationFailureCode {
    TRUNCATED_HEADER,
    UNKNOWN_MESSAGE_TYPE,
    NEGATIVE_PAYLOAD_LENGTH,
    PAYLOAD_LENGTH_MISMATCH,
    PAYLOAD_EXCEEDS_MAX_SIZE,
    HELLO_PAYLOAD_SIZE_INVALID,
    HANDSHAKE_PAYLOAD_TOO_SHORT,
    UPDATE_PAYLOAD_SIZE_INVALID,
    CHUNK_PAYLOAD_TOO_SHORT,
    CHUNK_ACK_PAYLOAD_TOO_SHORT,
    DELIVERY_ACK_PAYLOAD_SIZE_INVALID,
    NACK_PAYLOAD_SIZE_INVALID,
    KEEPALIVE_PAYLOAD_NOT_EMPTY,
    BROADCAST_PAYLOAD_TOO_SHORT,
    BROADCAST_MAX_HOPS_INVALID,
    ROUTED_MESSAGE_PAYLOAD_TOO_SHORT,
    HOP_LIMIT_EXCEEDED,
    RESUME_REQUEST_PAYLOAD_SIZE_INVALID,
    ROTATION_ANNOUNCEMENT_PAYLOAD_SIZE_INVALID,
}
