#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/update-package-swift.sh --version <tag> --checksum <sha256> [options]

Generates or verifies the SwiftPM Package.swift binaryTarget manifest for the
MeshLink XCFramework release artifact.

Options:
  --version <tag>          Release tag, e.g. v0.1.0
  --checksum <sha256>      SwiftPM checksum for MeshLink.xcframework.zip
  --repository <owner/repo>
                           GitHub repository slug (default: inferred or trancee/meshlink)
  --package-file <path>    Package.swift path (default: Package.swift)
  --artifact-name <name>   Release asset name (default: MeshLink.xcframework.zip)
  --verify                 Verify the existing manifest instead of overwriting it
  --help                   Show this help text
EOF
}

infer_repository() {
  if [[ -n "${GITHUB_REPOSITORY:-}" ]]; then
    printf '%s\n' "$GITHUB_REPOSITORY"
    return
  fi

  local remote_url
  remote_url="$(git config --get remote.origin.url 2>/dev/null || true)"

  case "$remote_url" in
    git@github.com:*.git)
      printf '%s\n' "${remote_url#git@github.com:}" | sed 's/\.git$//'
      return
      ;;
    https://github.com/*/*.git)
      printf '%s\n' "${remote_url#https://github.com/}" | sed 's/\.git$//'
      return
      ;;
    https://github.com/*/*)
      printf '%s\n' "${remote_url#https://github.com/}"
      return
      ;;
  esac

  printf '%s\n' "trancee/meshlink"
}

VERSION=""
CHECKSUM=""
REPOSITORY=""
PACKAGE_FILE="Package.swift"
ARTIFACT_NAME="MeshLink.xcframework.zip"
VERIFY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      VERSION="$2"
      shift 2
      ;;
    --checksum)
      CHECKSUM="$2"
      shift 2
      ;;
    --repository)
      REPOSITORY="$2"
      shift 2
      ;;
    --package-file)
      PACKAGE_FILE="$2"
      shift 2
      ;;
    --artifact-name)
      ARTIFACT_NAME="$2"
      shift 2
      ;;
    --verify)
      VERIFY=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$VERSION" || -z "$CHECKSUM" ]]; then
  echo "Both --version and --checksum are required." >&2
  usage >&2
  exit 1
fi

if [[ -z "$REPOSITORY" ]]; then
  REPOSITORY="$(infer_repository)"
fi

PACKAGE_URL="https://github.com/${REPOSITORY}/releases/download/${VERSION}/${ARTIFACT_NAME}"
EXPECTED_FILE="$(mktemp)"
trap 'rm -f "$EXPECTED_FILE"' EXIT

cat > "$EXPECTED_FILE" <<EOF
// swift-tools-version: 5.9
// Generated by scripts/update-package-swift.sh.
// Run this script before tagging a release so the binaryTarget URL and checksum
// match the GitHub release asset uploaded by .github/workflows/release.yml.
import PackageDescription

let package = Package(
    name: "MeshLink",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(
            name: "MeshLink",
            targets: ["MeshLink"],
        ),
    ],
    targets: [
        .binaryTarget(
            name: "MeshLink",
            url: "${PACKAGE_URL}",
            checksum: "${CHECKSUM}",
        ),
    ],
)
EOF

if [[ "$VERIFY" == true ]]; then
  if [[ ! -f "$PACKAGE_FILE" ]]; then
    echo "Package manifest not found: $PACKAGE_FILE" >&2
    exit 1
  fi

  if ! cmp -s "$PACKAGE_FILE" "$EXPECTED_FILE"; then
    echo "Package.swift does not match the expected release manifest." >&2
    diff -u "$PACKAGE_FILE" "$EXPECTED_FILE" >&2 || true
    exit 1
  fi
else
  cat "$EXPECTED_FILE" > "$PACKAGE_FILE"
fi

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "package_url=$PACKAGE_URL"
    echo "package_file=$PACKAGE_FILE"
  } >> "$GITHUB_OUTPUT"
fi

echo "PACKAGE_FILE=$PACKAGE_FILE"
echo "PACKAGE_URL=$PACKAGE_URL"
